### ISSUE TITLE
Whirlpool hash incorrectly calculated for string longer than 31 characters

### ISSUE THREAD

**Issue by PhoneixS** [nf404/crypto-api#11]
When you use a string with a length of 32 characters or more it returns an incorrect hash. I'm using 0.8.0 version as I need compatibility with Typescript which isn't compatible with ".msj" files yet.

I have a very simple angular service:
```

import { Injectable } from '@angular/core';

import CryptoApi from 'crypto-api';


@Injectable({
  providedIn: 'root'
})
export class EncriptacionService {

  constructor() { }

  /**
   * Calcula el hash del texto indicado y devuelve su hash en hexadecimal (minusculas).
   * @param texto El texto utf que se quiere encriptar.
   * @returns El hash en haxadecimal del texto que se pasó.
   */
  public whirlpoolUtf(texto: string): string {

    const whirlpool = CryptoApi.getHasher('whirlpool');
    whirlpool.update(CryptoApi.encoder.fromUtf(texto));
    const pswHash = whirlpool.finalize();

    return String(CryptoApi.encoder.toHex(pswHash));

  }

}

```

For example, I have this jasmine test:

```
import { TestBed, inject } from '@angular/core/testing';

import { EncriptacionService } from './encriptacion.service';

fdescribe('EncriptacionService', () => {
  beforeEach(() => {
    TestBed.configureTestingModule({
      providers: [EncriptacionService]
    });
  });

  it('should be created', inject([EncriptacionService], (service: EncriptacionService) => {
    expect(service).toBeTruthy();
  }));

  it('should calculate empty password hashes', inject([EncriptacionService], (service: EncriptacionService) => {

    // tslint:disable-next-line:max-line-length
    expect(service.whirlpoolUtf('')).toEqual('19fa61d75522a4669b44e39c1d2e1726c530232130d407f89afee0964997f7a73e83be698b288febcf88e3e03c4f0757ea8964e59b63d93708b138cc42a66eb3');

  }));

  it('should calculate standar password hashes', inject([EncriptacionService], (service: EncriptacionService) => {

    // tslint:disable-next-line:max-line-length
    expect(service.whirlpoolUtf('The quick brown fox jumps over the lazy dog')).toEqual('b97de512e91e3828b40d2b0fdce9ceb3c4a71f9bea8d88e75c4fa854df36725fd2b52eb6544edcacd6f8beddfea403cb55ae31f03ad62a5ef54e42ee82c3fb35');

  }));

  it('should calculate small password hashes', inject([EncriptacionService], (service: EncriptacionService) => {

    // tslint:disable-next-line:max-line-length
    expect(service.whirlpoolUtf('ItIsOk')).toEqual('56a0a18d7054ee0ad8de79f605f69974f13aa17bb546c0998ae9656f59f3facb79da22feacef476af5655cffc6574e3a6f0b260b7b813b57af138be045efd589');

  }));

  it('should calculate 31bytes password hashes', inject([EncriptacionService], (service: EncriptacionService) => {

    // tslint:disable-next-line:max-line-length
    expect(service.whirlpoolUtf('1234567890123456789012345678901')).toEqual('998b2ea00979a006555ecb5d2742663d8b41cb68eb3260240072d5fe8d5f3a17b82e6a5bef44e8132f0292313c3790fefa741e498030ad59d21e93bd09434ba0');

  }));

  it('should calculate 32bytes password hashes', inject([EncriptacionService], (service: EncriptacionService) => {

    // tslint:disable-next-line:max-line-length
    expect(service.whirlpoolUtf('12345678901234567890123456789012')).toEqual('089df308138da5c5cfe63a602d45fb608de6b1bb037703fa30eb87b7c5e59d339f9efd40f0460ec107247d67288e4b229058115cf2fd6dfb5eff34d32d0e2bb8');

  }));

  it('should calculate 33bytes password hashes', inject([EncriptacionService], (service: EncriptacionService) => {

    // tslint:disable-next-line:max-line-length
    expect(service.whirlpoolUtf('123456789012345678901234567890123')).toEqual('1b5bb628742042db83ee317dbb59771e1619ea100b9bceb11fe3b2b6d2f221a304be53ec090feb65967ada04ef8908d99e28faa0e831851787f060902b9a2850');

  }));

  it('should calculate 34bytes password hashes', inject([EncriptacionService], (service: EncriptacionService) => {

    // tslint:disable-next-line:max-line-length
    expect(service.whirlpoolUtf('1234567890123456789012345678901234')).toEqual('30fea13bf7cfb407b16170dd27604b301696fdaeb981bf9ed6dcdf5439b026743cff3ef9e5286099da13a1ecac30f48bd2b06c94e86cd75f44abf18f3e808cc8');

  }));

  it('should calculate 35bytes password hashes', inject([EncriptacionService], (service: EncriptacionService) => {

    // tslint:disable-next-line:max-line-length
    expect(service.whirlpoolUtf('12345678901234567890123456789012345')).toEqual('32fb1d6dc027fadb09f116c58b7c9e526b5420b47c4b9c21e1493cde08464c0af2dd83c034ea7d05a4e8956d8ca2809f1620b22e6bc6cc3c74c21f2e4a6072a4');

  }));

  it('should calculate 36bytes password hashes', inject([EncriptacionService], (service: EncriptacionService) => {

    // tslint:disable-next-line:max-line-length
    expect(service.whirlpoolUtf('123456789012345678901234567890123456')).toEqual('48de730fa3808e6fed742dc0593cdf6b17aca9e3c6b98bfc6e92528afa0264082366f93a006d692c08cda996da3db7497f6af7dba11455acec3ab242e6e58761');

  }));

  it('should calculate 37bytes password hashes', inject([EncriptacionService], (service: EncriptacionService) => {

    // tslint:disable-next-line:max-line-length
    expect(service.whirlpoolUtf('1234567890123456789012345678901234567')).toEqual('e9661ba26736a6066770e347bb1e70e4825626d80cb9d873ebda1d8384b4d92e26bcf86ba076f6aa165a34f3b87fd80c8c682660427140484b1ac321dd5c1bd2');

  }));

  it('should calculate 38bytes password hashes', inject([EncriptacionService], (service: EncriptacionService) => {

    // tslint:disable-next-line:max-line-length
    expect(service.whirlpoolUtf('12345678901234567890123456789012345678')).toEqual('cca33700fb5a238384761a9f554b6bc98e6dab249cd37986ae8b44ae47f6b8e29d2b79e2a5b48055bd19312936be5f03a4bb4fc53f52740d897f711c72e68291');

  }));

});

```

And here are the failures:

```
EncriptacionService should calculate standar password hashes
Expected 'ed14e654fb0b26a66e941a886e05b65842bb0bd0577cc9e32a79fafe3d6edad6f7707980e2fd127169b354fdc2f200fa6f5a77e2516ce3b62dccdcd4448d9e3d' to equal 'b97de512e91e3828b40d2b0fdce9ceb3c4a71f9bea8d88e75c4fa854df36725fd2b52eb6544edcacd6f8beddfea403cb55ae31f03ad62a5ef54e42ee82c3fb35'.
Error: Expected 'ed14e654fb0b26a66e941a886e05b65842bb0bd0577cc9e32a79fafe3d6edad6f7707980e2fd127169b354fdc2f200fa6f5a77e2516ce3b62dccdcd4448d9e3d' to equal 'b97de512e91e3828b40d2b0fdce9ceb3c4a71f9bea8d88e75c4fa854df36725fd2b52eb6544edcacd6f8beddfea403cb55ae31f03ad62a5ef54e42ee82c3fb35'.
    at stack (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:2338:17)
    at buildExpectationResult (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:2308:14)
    at Spec.expectationResultFactory (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:858:18)
    at Spec.addExpectationResult (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:487:34)
    at Expectation.addExpectationResult (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:802:21)
    at Expectation.toEqual (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:2252:12)
    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/src/app/shared/encriptacion.service.spec.ts:26:81)
    at TestBed.push../node_modules/@angular/core/fesm5/testing.js.TestBed.execute (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm5/testing.js:1262:1)
    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm5/testing.js:1415:29)
    at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:388:1)
EncriptacionService should calculate 32bytes password hashes
Expected '95c65393344c9cbd8f350ca6e7c8c7f21c142055389f7b833193db8b29f8e0acd825e5d33762155c0b35374762e04703257a8befcbfbd0bab6dda5234449b4f0' to equal '089df308138da5c5cfe63a602d45fb608de6b1bb037703fa30eb87b7c5e59d339f9efd40f0460ec107247d67288e4b229058115cf2fd6dfb5eff34d32d0e2bb8'.
Error: Expected '95c65393344c9cbd8f350ca6e7c8c7f21c142055389f7b833193db8b29f8e0acd825e5d33762155c0b35374762e04703257a8befcbfbd0bab6dda5234449b4f0' to equal '089df308138da5c5cfe63a602d45fb608de6b1bb037703fa30eb87b7c5e59d339f9efd40f0460ec107247d67288e4b229058115cf2fd6dfb5eff34d32d0e2bb8'.
    at stack (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:2338:17)
    at buildExpectationResult (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:2308:14)
    at Spec.expectationResultFactory (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:858:18)
    at Spec.addExpectationResult (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:487:34)
    at Expectation.addExpectationResult (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:802:21)
    at Expectation.toEqual (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:2252:12)
    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/src/app/shared/encriptacion.service.spec.ts:47:70)
    at TestBed.push../node_modules/@angular/core/fesm5/testing.js.TestBed.execute (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm5/testing.js:1262:1)
    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm5/testing.js:1415:29)
    at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:388:1)
EncriptacionService should calculate 33bytes password hashes
Expected '14a142fd47c240575c75677fd3007604e8537f0d2cdf0d32450ea83d261ee722c6d2b9431c047fc545a6541d5762a0591274a11187bdafc44a44f978c173e670' to equal '1b5bb628742042db83ee317dbb59771e1619ea100b9bceb11fe3b2b6d2f221a304be53ec090feb65967ada04ef8908d99e28faa0e831851787f060902b9a2850'.
Error: Expected '14a142fd47c240575c75677fd3007604e8537f0d2cdf0d32450ea83d261ee722c6d2b9431c047fc545a6541d5762a0591274a11187bdafc44a44f978c173e670' to equal '1b5bb628742042db83ee317dbb59771e1619ea100b9bceb11fe3b2b6d2f221a304be53ec090feb65967ada04ef8908d99e28faa0e831851787f060902b9a2850'.
    at stack (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:2338:17)
    at buildExpectationResult (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:2308:14)
    at Spec.expectationResultFactory (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:858:18)
    at Spec.addExpectationResult (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:487:34)
    at Expectation.addExpectationResult (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:802:21)
    at Expectation.toEqual (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:2252:12)
    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/src/app/shared/encriptacion.service.spec.ts:54:71)
    at TestBed.push../node_modules/@angular/core/fesm5/testing.js.TestBed.execute (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm5/testing.js:1262:1)
    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm5/testing.js:1415:29)
    at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:388:1)
EncriptacionService should calculate 34bytes password hashes
Expected '7c3d50d61f7061756f5feabea5f5efdb7740bf67d153819c084d0bcd23da55c5705067d5fa1b02761eb6d4e22de16de0498510fa452a66cbffdd3c5b4dbeb65e' to equal '30fea13bf7cfb407b16170dd27604b301696fdaeb981bf9ed6dcdf5439b026743cff3ef9e5286099da13a1ecac30f48bd2b06c94e86cd75f44abf18f3e808cc8'.
Error: Expected '7c3d50d61f7061756f5feabea5f5efdb7740bf67d153819c084d0bcd23da55c5705067d5fa1b02761eb6d4e22de16de0498510fa452a66cbffdd3c5b4dbeb65e' to equal '30fea13bf7cfb407b16170dd27604b301696fdaeb981bf9ed6dcdf5439b026743cff3ef9e5286099da13a1ecac30f48bd2b06c94e86cd75f44abf18f3e808cc8'.
    at stack (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:2338:17)
    at buildExpectationResult (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:2308:14)
    at Spec.expectationResultFactory (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:858:18)
    at Spec.addExpectationResult (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:487:34)
    at Expectation.addExpectationResult (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:802:21)
    at Expectation.toEqual (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:2252:12)
    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/src/app/shared/encriptacion.service.spec.ts:61:72)
    at TestBed.push../node_modules/@angular/core/fesm5/testing.js.TestBed.execute (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm5/testing.js:1262:1)
    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm5/testing.js:1415:29)
    at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:388:1)
EncriptacionService should calculate 35bytes password hashes
Expected '96a37e85071be46dab7e641e76551a9a0325c5e5dcb51d6d4c29833199bbf9e0afe456256255f25d548d4f49187f2d7e1d33fce3d6b5b24ba781f1f8b474e20d' to equal '32fb1d6dc027fadb09f116c58b7c9e526b5420b47c4b9c21e1493cde08464c0af2dd83c034ea7d05a4e8956d8ca2809f1620b22e6bc6cc3c74c21f2e4a6072a4'.
Error: Expected '96a37e85071be46dab7e641e76551a9a0325c5e5dcb51d6d4c29833199bbf9e0afe456256255f25d548d4f49187f2d7e1d33fce3d6b5b24ba781f1f8b474e20d' to equal '32fb1d6dc027fadb09f116c58b7c9e526b5420b47c4b9c21e1493cde08464c0af2dd83c034ea7d05a4e8956d8ca2809f1620b22e6bc6cc3c74c21f2e4a6072a4'.
    at stack (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:2338:17)
    at buildExpectationResult (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:2308:14)
    at Spec.expectationResultFactory (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:858:18)
    at Spec.addExpectationResult (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:487:34)
    at Expectation.addExpectationResult (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:802:21)
    at Expectation.toEqual (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:2252:12)
    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/src/app/shared/encriptacion.service.spec.ts:68:73)
    at TestBed.push../node_modules/@angular/core/fesm5/testing.js.TestBed.execute (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm5/testing.js:1262:1)
    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm5/testing.js:1415:29)
    at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:388:1)
EncriptacionService should calculate 36bytes password hashes
Expected '929e367ae4ade4c3e0e640b3fe074de8c9d1a60546b70ea3bff85173a65a2c1efcbfbb8c653a2486c11cb46cb91d5e92658b999f55bda96a4f8277f8c7c24269' to equal '48de730fa3808e6fed742dc0593cdf6b17aca9e3c6b98bfc6e92528afa0264082366f93a006d692c08cda996da3db7497f6af7dba11455acec3ab242e6e58761'.
Error: Expected '929e367ae4ade4c3e0e640b3fe074de8c9d1a60546b70ea3bff85173a65a2c1efcbfbb8c653a2486c11cb46cb91d5e92658b999f55bda96a4f8277f8c7c24269' to equal '48de730fa3808e6fed742dc0593cdf6b17aca9e3c6b98bfc6e92528afa0264082366f93a006d692c08cda996da3db7497f6af7dba11455acec3ab242e6e58761'.
    at stack (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:2338:17)
    at buildExpectationResult (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:2308:14)
    at Spec.expectationResultFactory (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:858:18)
    at Spec.addExpectationResult (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:487:34)
    at Expectation.addExpectationResult (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:802:21)
    at Expectation.toEqual (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:2252:12)
    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/src/app/shared/encriptacion.service.spec.ts:75:74)
    at TestBed.push../node_modules/@angular/core/fesm5/testing.js.TestBed.execute (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm5/testing.js:1262:1)
    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm5/testing.js:1415:29)
    at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:388:1)
EncriptacionService should calculate 37bytes password hashes
Expected '6336c8aa1e5449d0cfce6f11b206070042dfbd5f6959f3a41e94beac750f99fd3f5efdd5e949169d8574609d928f131c104e8ad93d6b2bc7ffc91c480e65d582' to equal 'e9661ba26736a6066770e347bb1e70e4825626d80cb9d873ebda1d8384b4d92e26bcf86ba076f6aa165a34f3b87fd80c8c682660427140484b1ac321dd5c1bd2'.
Error: Expected '6336c8aa1e5449d0cfce6f11b206070042dfbd5f6959f3a41e94beac750f99fd3f5efdd5e949169d8574609d928f131c104e8ad93d6b2bc7ffc91c480e65d582' to equal 'e9661ba26736a6066770e347bb1e70e4825626d80cb9d873ebda1d8384b4d92e26bcf86ba076f6aa165a34f3b87fd80c8c682660427140484b1ac321dd5c1bd2'.
    at stack (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:2338:17)
    at buildExpectationResult (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:2308:14)
    at Spec.expectationResultFactory (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:858:18)
    at Spec.addExpectationResult (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:487:34)
    at Expectation.addExpectationResult (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:802:21)
    at Expectation.toEqual (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:2252:12)
    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/src/app/shared/encriptacion.service.spec.ts:82:75)
    at TestBed.push../node_modules/@angular/core/fesm5/testing.js.TestBed.execute (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm5/testing.js:1262:1)
    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm5/testing.js:1415:29)
    at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:388:1)
EncriptacionService should calculate 38bytes password hashes
Expected '187c19a959e6d02a1fa64e7295bab0b2aeda35a343ad7ac96a58cb82d356c12c403fa81c86c3bd826d6fa09d22c2d5f9c72ce3b44a0c8a259d25e2abfe74c2f0' to equal 'cca33700fb5a238384761a9f554b6bc98e6dab249cd37986ae8b44ae47f6b8e29d2b79e2a5b48055bd19312936be5f03a4bb4fc53f52740d897f711c72e68291'.
Error: Expected '187c19a959e6d02a1fa64e7295bab0b2aeda35a343ad7ac96a58cb82d356c12c403fa81c86c3bd826d6fa09d22c2d5f9c72ce3b44a0c8a259d25e2abfe74c2f0' to equal 'cca33700fb5a238384761a9f554b6bc98e6dab249cd37986ae8b44ae47f6b8e29d2b79e2a5b48055bd19312936be5f03a4bb4fc53f52740d897f711c72e68291'.
    at stack (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:2338:17)
    at buildExpectationResult (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:2308:14)
    at Spec.expectationResultFactory (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:858:18)
    at Spec.addExpectationResult (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:487:34)
    at Expectation.addExpectationResult (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:802:21)
    at Expectation.toEqual (http://localhost:9876/base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?73bc53d3671677e6a093fc74e4f9bcde57e5f7ad:2252:12)
    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/src/app/shared/encriptacion.service.spec.ts:89:76)
    at TestBed.push../node_modules/@angular/core/fesm5/testing.js.TestBed.execute (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm5/testing.js:1262:1)
    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm5/testing.js:1415:29)
    at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:388:1)
```

**Comment by PhoneixS** [comment]
A list of which tests passed (ok) and which don't pass (KO):

should be created ok
should calculate empty password hashes ok
should calculate standar password hashes KO
should calculate small password hashes ok
should calculate 31bytes password hashes ok
should calculate 32bytes password hashes KO
should calculate 33bytes password hashes KO
should calculate 34bytes password hashes KO
should calculate 35bytes password hashes KO
should calculate 36bytes password hashes KO
should calculate 37bytes password hashes KO
should calculate 38bytes password hashes KO

**Comment by nf404** [comment]
Confirmed.
Bug in padding calculation for all 3 types of Whirlpool

**Comment by nf404** [comment]
also I add precompiled es5 file for nodejs so u can use it with version 0.8.3
```js
'use strict';

const CryptoApi = require('crypto-api');

const whirlpool = CryptoApi.getHasher('whirlpool');
whirlpool.update(CryptoApi.encoder.fromUtf('test'));
const pswHash = whirlpool.finalize();
console.log(CryptoApi.encoder.toHex(pswHash));
```
